"""empty message

Revision ID: 43cb111f27ae
Revises: 6e4aade18c7b
Create Date: 2018-04-11 08:47:31.684122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cb111f27ae'
down_revision = '6e4aade18c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart', sa.Column('legend', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chart', 'legend')
    # ### end Alembic commands ###
