"""empty message

Revision ID: a7f063c148d3
Revises: 43cb111f27ae
Create Date: 2018-04-11 14:57:14.526975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7f063c148d3'
down_revision = '43cb111f27ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart', sa.Column('date_format', sa.String(length=255), nullable=True))
    op.drop_column('chart', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('chart', 'date_format')
    # ### end Alembic commands ###
