"""empty message

Revision ID: a89969b41dad
Revises: ef60b543068a
Create Date: 2018-08-06 15:33:00.279879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89969b41dad'
down_revision = 'ef60b543068a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('patronymic', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_num', sa.String(length=25), nullable=True),
    sa.Column('decomission_date', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ts_resposibles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ts', sa.Integer(), nullable=True),
    sa.Column('associate_id', sa.Integer(), nullable=True),
    sa.Column('parrent_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['associate_id'], ['associates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_ts'], ['ts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parrent_id'], ['ts_resposibles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ts_resposibles')
    op.drop_table('ts')
    op.drop_table('associates')
    # ### end Alembic commands ###
